"""Initial migration

Revision ID: 086c23c5b08a
Revises: 
Create Date: 2025-04-16 17:22:03.646716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086c23c5b08a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payer_info', sa.Column('relation_to_students', sa.String(), nullable=False))
    op.add_column('payer_info', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payer_info_id'), 'payer_info', ['id'], unique=False)
    op.create_foreign_key(None, 'payer_info', 'payments', ['payment_id'], ['id'])
    op.drop_column('payer_info', 'relationship')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payer_info', sa.Column('relationship', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payer_info', type_='foreignkey')
    op.drop_index(op.f('ix_payer_info_id'), table_name='payer_info')
    op.drop_column('payer_info', 'payment_id')
    op.drop_column('payer_info', 'relation_to_students')
    # ### end Alembic commands ###
