"""add extra_fees_name to exam_fees

Revision ID: 27dbf3701a8a
Revises: b5a757fc31a9
Create Date: 2026-01-31 19:30:37.648274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dbf3701a8a'
down_revision: Union[str, None] = 'b5a757fc31a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_fees', sa.Column('extra_fees_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_fees', 'extra_fees_name')
    # ### end Alembic commands ###
