"""added exam payments details

Revision ID: 43e47d62fafb
Revises: 3b93c462407c
Create Date: 2025-05-18 03:01:12.318551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '43e47d62fafb'
down_revision: Union[str, None] = '3b93c462407c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if paymentstatus enum exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    enums = inspector.get_enums()
    enum_exists = any(e['name'] == 'paymentstatus' for e in enums)
    
    # Create enum if it doesn't exist
    if not enum_exists:
        paymentstatus = postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus')
        paymentstatus.create(conn)
    
    op.create_table('exam_fees',
    sa.Column('exam_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_fees_id'), 'exam_fees', ['id'], unique=False)
    op.create_table('exam_payments',
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus', create_type=False), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_fees.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index(op.f('ix_exam_payments_id'), 'exam_payments', ['id'], unique=False)
    op.create_table('student_exam_payment_status',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('is_fully_paid', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_fees.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_exam_payment_status_id'), 'student_exam_payment_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_exam_payment_status_id'), table_name='student_exam_payment_status')
    op.drop_table('student_exam_payment_status')
    op.drop_index(op.f('ix_exam_payments_id'), table_name='exam_payments')
    op.drop_table('exam_payments')
    op.drop_index(op.f('ix_exam_fees_id'), table_name='exam_fees')
    op.drop_table('exam_fees')
    # ### end Alembic commands ###
