"""added discount info

Revision ID: 61ec8b6423ca
Revises: 8ba7c6fd77a4
Create Date: 2025-04-18 20:41:02.240708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ec8b6423ca'
down_revision: Union[str, None] = '8ba7c6fd77a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.drop_column('students', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('students', 'discount_amount')
    op.drop_column('students', 'discount_percentage')
    # ### end Alembic commands ###
