"""added fees

Revision ID: 7ea4beae096d
Revises: 6f4a281b9a65
Create Date: 2025-04-17 10:56:45.582009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea4beae096d'
down_revision: Union[str, None] = '6f4a281b9a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('reg_number', sa.String(), nullable=True))
    op.add_column('students', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('school_fees_paid', sa.Boolean(), nullable=True))
    op.drop_column('students', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'school_fees_paid')
    op.drop_column('students', 'discount')
    op.drop_column('students', 'reg_number')
    # ### end Alembic commands ###
