"""create clubs

Revision ID: 914ce998e7e6
Revises: a1b2c3d4e5f6
Create Date: 2026-01-12 15:38:38.932376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914ce998e7e6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_fees', sa.Column('allows_installments', sa.Boolean(), nullable=False))
    op.add_column('exam_fees', sa.Column('applicable_grades', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_fees', 'applicable_grades')
    op.drop_column('exam_fees', 'allows_installments')
    # ### end Alembic commands ###
