"""made payment reference to not be unique

Revision ID: 93d6a3e9b6db
Revises: ed109a2f3fd7
Create Date: 2025-05-27 21:27:45.928913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93d6a3e9b6db'
down_revision: Union[str, None] = 'ed109a2f3fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_multiple_exam_payments_id', table_name='multiple_exam_payments')
    op.drop_table('multiple_exam_payments')
    op.drop_constraint('exam_payments_payment_reference_key', 'exam_payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('exam_payments_payment_reference_key', 'exam_payments', ['payment_reference'], postgresql_nulls_not_distinct=False)
    op.create_table('multiple_exam_payments',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exam_payments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), autoincrement=False, nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='multiple_exam_payments_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='multiple_exam_payments_pkey'),
    sa.UniqueConstraint('payment_reference', name='multiple_exam_payments_payment_reference_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_multiple_exam_payments_id', 'multiple_exam_payments', ['id'], unique=False)
    # ### end Alembic commands ###
