"""payment changes

Revision ID: b5a757fc31a9
Revises: b7c1a2d3e4f5
Create Date: 2026-01-19 12:18:25.156062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a757fc31a9'
down_revision: Union[str, None] = 'b7c1a2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payment_items_item_type'), 'payment_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_payment_items_payment_id'), 'payment_items', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_items_payment_id'), table_name='payment_items')
    op.drop_index(op.f('ix_payment_items_item_type'), table_name='payment_items')
    # ### end Alembic commands ###
