"""add_date_columns_to_exam_payments

Revision ID: db55ac5d8324
Revises: 93d6a3e9b6db
Create Date: 2025-06-01 23:13:05.678416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db55ac5d8324'
down_revision: Union[str, None] = '93d6a3e9b6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_payments', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('exam_payments', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'date_updated')
    op.drop_column('payments', 'date_created')
    op.drop_column('exam_payments', 'date_updated')
    op.drop_column('exam_payments', 'date_created')
    # ### end Alembic commands ###
