"""Initial migration

Revision ID: e3df45849480
Revises: 914ce998e7e6
Create Date: 2026-01-17 00:38:24.680028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3df45849480'
down_revision: Union[str, None] = '914ce998e7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_student',
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'student_id')
    )
    op.drop_index('ix_payer_info_id', table_name='payer_info')
    op.drop_table('payer_info')
    op.alter_column('club_memberships', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('club_memberships', 'club_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('club_memberships', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('clubs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('clubs_id_seq'::regclass)"))
    op.alter_column('exam_fees', 'applicable_grades',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('exam_fees', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('exam_fees_id_seq'::regclass)"))
    op.add_column('exam_payments', sa.Column('payer_id', sa.String(), nullable=True))
    op.alter_column('exam_payments', 'exam_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('exam_payments', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('exam_payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'exam_payments', 'parents', ['payer_id'], ['id'])
    op.alter_column('fees', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('parents', sa.Column('auth_id', sa.String(), nullable=False))
    op.add_column('parents', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('parents', sa.Column('last_name', sa.String(), nullable=False))
    op.alter_column('parents', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('parents_id_seq'::regclass)"))
    op.drop_constraint('parents_email_key', 'parents', type_='unique')
    op.create_index(op.f('ix_parents_auth_id'), 'parents', ['auth_id'], unique=True)
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=True)
    op.create_index(op.f('ix_parents_phone'), 'parents', ['phone'], unique=True)
    op.drop_column('parents', 'name')
    op.drop_column('parents', 'address')
    op.add_column('payments', sa.Column('payer_id', sa.String(), nullable=True))
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'payments', 'parents', ['payer_id'], ['id'])
    op.alter_column('student_exam_payment_status', 'student_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('student_exam_payment_status', 'exam_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('student_exam_payment_status', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('students', sa.Column('year_group', sa.Enum('YEAR_6', 'YEAR_7', 'YEAR_8', 'YEAR_9', 'YEAR_10', 'YEAR_11', 'YEAR_12', name='yeargroup'), nullable=False))
    op.add_column('students', sa.Column('class_name', sa.Enum('AMBER', 'EMERALD', 'IVORY', 'SPRING', 'DIAMOND', name='classname'), nullable=False))
    op.add_column('students', sa.Column('outstanding_balance', sa.Float(), nullable=True))
    op.alter_column('students', 'reg_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_reg_number'), 'students', ['reg_number'], unique=True)
    op.drop_constraint('students_parent_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'discount_amount')
    op.drop_column('students', 'parent_id')
    op.drop_column('students', 'grade')
    op.drop_column('students', 'discount_percentage')
    op.drop_column('students', 'school_fees_paid')
    op.drop_column('students', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('school_fees_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('discount_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('students_parent_id_fkey', 'students', 'parents', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_students_reg_number'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.alter_column('students', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('students', 'reg_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('students', 'outstanding_balance')
    op.drop_column('students', 'class_name')
    op.drop_column('students', 'year_group')
    op.alter_column('student_exam_payment_status', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('student_exam_payment_status', 'exam_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('student_exam_payment_status', 'student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('payments', 'payer_id')
    op.add_column('parents', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parents', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_parents_phone'), table_name='parents')
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_index(op.f('ix_parents_auth_id'), table_name='parents')
    op.create_unique_constraint('parents_email_key', 'parents', ['email'])
    op.alter_column('parents', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('parents_id_seq'::regclass)"))
    op.drop_column('parents', 'last_name')
    op.drop_column('parents', 'first_name')
    op.drop_column('parents', 'auth_id')
    op.alter_column('fees', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'exam_payments', type_='foreignkey')
    op.alter_column('exam_payments', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('exam_payments', 'student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exam_payments', 'exam_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('exam_payments', 'payer_id')
    op.alter_column('exam_fees', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('exam_fees_id_seq'::regclass)"))
    op.alter_column('exam_fees', 'applicable_grades',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('clubs', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('clubs_id_seq'::regclass)"))
    op.alter_column('club_memberships', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('club_memberships', 'club_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('club_memberships', 'student_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('payer_info',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relation_to_students', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exam_payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['exam_payment_id'], ['exam_payments.id'], name='payer_info_exam_payment_id_fkey'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='payer_info_payment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payer_info_pkey')
    )
    op.create_index('ix_payer_info_id', 'payer_info', ['id'], unique=False)
    op.drop_table('parent_student')
    # ### end Alembic commands ###
