"""added extra fees field for exams

Revision ID: ed109a2f3fd7
Revises: ee439f71f363
Create Date: 2025-05-22 17:50:55.226334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed109a2f3fd7'
down_revision: Union[str, None] = 'ee439f71f363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_fees', sa.Column('extra_fees', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_fees', 'extra_fees')
    # ### end Alembic commands ###
