"""added exam relationship for payment status

Revision ID: ee439f71f363
Revises: aae8600b9b68
Create Date: 2025-05-20 12:10:07.057699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee439f71f363'
down_revision: Union[str, None] = 'aae8600b9b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payer_info', sa.Column('exam_payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payer_info', 'exam_payments', ['exam_payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payer_info', type_='foreignkey')
    op.drop_column('payer_info', 'exam_payment_id')
    # ### end Alembic commands ###
