"""update payment info accordingly

Revision ID: f88317c159d2
Revises: 086c23c5b08a
Create Date: 2025-04-16 17:54:44.192706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88317c159d2'
down_revision: Union[str, None] = '086c23c5b08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_memberships', sa.Column('payment_confirmed', sa.Boolean(), nullable=True))
    op.drop_constraint('payments_parent_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payments_parent_id_fkey', 'payments', 'parents', ['parent_id'], ['id'])
    op.drop_column('club_memberships', 'payment_confirmed')
    # ### end Alembic commands ###
